language: ruby
cache: bundler
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.5.3"
gemfile:
  - "gemfiles/delayed_job_3.gemfile"
  - "gemfiles/delayed_job_4.gemfile"
matrix:
  exclude:
  - rvm: "2.5.3"
    gemfile: "gemfiles/delayed_job_3.gemfile"
before_install:
  # Travis bundler versions are quite out of date and can cause install errors
  # see: https://github.com/rubygems/rubygems/issues/1419
  - "gem install bundler"
